version: 2
updates:
  # Maintain dependencies for container images
  - package-ecosystem: "docker"
    # blocked due to: https://github.com/dependabot/dependabot-core/issues/2178
    directory: "/"
    schedule:
      interval: "daily"