---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
